additionalProperties:
  sortParamsByRequiredFlag: true
  ensureUniqueParams: true
  allowUnicodeIdentifiers: false
  modelPackage: Model
  apiPackage: Api
  variableNamingConvention: camelCase
  invokerPackage: ChannelEngine\Merchant\ApiClient
  packagePath: ''
  composerVendorName: davidepastore
  gitUserId: channelengine
  composerProjectName: merchant-api-client-php
  gitRepoId: merchant-api-client-php
  hideGenerationTimestamp: true
