on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  generate-php-client:
    runs-on: ubuntu-latest
    name: Generate PHP Client
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: set-version
        run: |
          wget -O swagger.json "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          version=$(cat swagger.json | jq '.info.version')
          echo "The version is ${version}"
          echo "packageVersion=${version}" >> $GITHUB_OUTPUT



      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: "https://demo.channelengine.net/api/swagger/merchant/swagger.json"
          #config-file: /swagger-config.json
          command-args: --artifact-version=${{ steps.set-version.outputs.packageVersion }}

      # Do something with the generated client (likely publishing it somewhere)
      - name: Do something with the client
        run: |
          ls
          cd php-client
          ls
          cat composer.json
      